services:
  usuba:
    build:
      context: .
      dockerfile: ./rust/usuba/Dockerfile
      tags:
        - 'usuba:local'
    network_mode: 'host'
    environment:
      UPSTREAM: 'localhost:5173'
