name: Build Docker Images

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  REGISTRY: ghcr.io
  RUNTIME_BASE_IMAGE: debian:latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          cache-from: commontools/base
          push: true
          provenance: true
          tags:
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/base:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/base:latest
          build-args: |
            BASE_IMAGE=${{ env.RUNTIME_BASE_IMAGE }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner }}/base
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
